spring:
  datasource:
  #正式库
#    username: service
#    password: rN1^oxMk8gqxU1Wj
#    url: jdbc:mysql://rds9ofcm376jwwdtqs56public.mysql.rds.aliyuncs.com:3306/service?useUnicode=true&user=service&password=rN1^oxMk8gqxU1Wj
   #本地库
    url: jdbc:mysql://localhost:3306/miaosos
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false


  redis:
  # Redis服务器地址
    host: 47.104.135.224
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 12345678

miaosos:
  base:
    projectName: 法视云
    sessionUser: sessionUser
    resourcePath: 'http://8snf0ca1cc2m.d0o9w1n.t3re.miaosos.com'
logging:
  path: /var/miaosos-web
  level:
    com:
      miaosos:
        mapper: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
